// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vadc/heartbeat/service/GrpcEventService.proto

package vadc.heartbeat.service;

public interface EventRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vadc.heartbeat.service.EventRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string body = 1;</code>
   */
  java.lang.String getBody();
  /**
   * <code>string body = 1;</code>
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
