// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vadc/heartbeat/service/GrpcEventService.proto

package vadc.heartbeat.service;

public interface EventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vadc.heartbeat.service.EventResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string payload = 2;</code>
   */
  java.lang.String getPayload();
  /**
   * <code>string payload = 2;</code>
   */
  com.google.protobuf.ByteString
      getPayloadBytes();

  /**
   * <code>string state = 3;</code>
   */
  java.lang.String getState();
  /**
   * <code>string state = 3;</code>
   */
  com.google.protobuf.ByteString
      getStateBytes();
}
