// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vadc/heartbeat/service/GrpcEventService.proto

package vadc.heartbeat.service;

public final class GrpcEventService {
  private GrpcEventService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vadc_heartbeat_service_EventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vadc_heartbeat_service_EventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vadc_heartbeat_service_EventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vadc_heartbeat_service_EventResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-vadc/heartbeat/service/GrpcEventServic" +
      "e.proto\022\026vadc.heartbeat.service\"\034\n\014Event" +
      "Request\022\014\n\004body\030\001 \001(\t\";\n\rEventResponse\022\n" +
      "\n\002id\030\001 \001(\t\022\017\n\007payload\030\002 \001(\t\022\r\n\005state\030\003 \001" +
      "(\t2e\n\014EventService\022U\n\006submit\022$.vadc.hear" +
      "tbeat.service.EventRequest\032%.vadc.heartb" +
      "eat.service.EventResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_vadc_heartbeat_service_EventRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vadc_heartbeat_service_EventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vadc_heartbeat_service_EventRequest_descriptor,
        new java.lang.String[] { "Body", });
    internal_static_vadc_heartbeat_service_EventResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_vadc_heartbeat_service_EventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vadc_heartbeat_service_EventResponse_descriptor,
        new java.lang.String[] { "Id", "Payload", "State", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
